Audits: {Avg Ball Time: '0:07', Avg Extra Balls: 0, Avg Game Time: '0:57', Avg Score: 61183,
  Balls Played: 375, Games Played: 125, Games Started: 108}
ClassicHighScoreData:
- {date: 'Fri Jan 30 19:46:43 2015', inits: CORIJN, score: 10000}
- {date: 'Fri Jan 29 10:54:23 2016', inits: ALVIN, score: 6350}
- {date: 'Fri Jan 30 20:48:04 2015', inits: 'MIGIEGEL  ', score: 5000}
- {date: 'Fri Jan 30 20:42:24 2015', inits: AAAAAAAAAA, score: 4000}
