Audits: {Avg Ball Time: '0:08', Avg Extra Balls: 0, Avg Game Time: '0:54', Avg Score: 60554,
  Balls Played: 366, Games Played: 122, Games Started: 105}
ClassicHighScoreData:
- {date: 'Fri Jan 30 19:46:43 2015', inits: REZA, score: 192746}
- {date: 'Fri Jan 30 20:48:04 2015', inits: 'MIGIEGEL  ', score: 182433}
- {date: 'Fri Jan 30 20:42:24 2015', inits: AAAAAAAAAA, score: 163468}
- {date: 'Fri Jan 30 20:25:55 2015', inits: KASPER TAN, score: 159160}
- {date: 'Fri Jan 30 21:12:01 2015', inits: STE, score: 145566}
