Audits: {Avg Ball Time: '0:07', Avg Extra Balls: 0, Avg Game Time: '1:02', Avg Score: 12670496981,
  Balls Played: 1279, Games Played: 422, Games Started: 356}
ClassicHighScoreData:
- {date: 'Tue Apr 17 08:27:32 2018', inits: STE, score: 1593270}
- {date: 'Tue Jun 19 09:25:39 2018', inits: FLORIS, score: 803110}
- {date: 'Tue Feb 13 09:43:31 2018', inits: STEVEN, score: 640450}
- {date: 'Fri Jan 12 15:16:50 2018', inits: MAC, score: 476580}
- {date: 'Fri Jan 12 16:43:41 2018', inits: TIM, score: 325180}
