# Configuration file for the generic GameLauncher for P-ROC
# Rename to Loader.yaml and modify for your particular configuration

# Customize this file to your own needs --note that if your game 
# is pre-fliptronic (i.e., as a flipper relay) then you need to
# specify a flipperEnable coil in your machine_config_file so 
# the launcher can enable your flippers for game selection.  
#
# The launcher uses switches:
#     - flipperLwR
#     - flipperLwL
#     - startButton
#   to navigate the game list.
# 
# most options should be obvious.
# Note that games that run via Python require a gamefile and gamepath
# whereas pinmame ROMs (Williams/FreeWPC) should have a ROM specified
# ROMs should be placed in the pinmame path.
##################################################################### 
machine_config_file: C:\P-ROC\pyprocgame-master\games\VXtra_start\config\Pinbot.yaml
title: 'PinBot 2'
instructions_line_1: 'Choose game with flippers'
instructions_line_2: 'then press START to select.'
pinmame:
    path: 'C:\P-ROC\pinmame_files\'
    nvram: 'C:\P-ROC\pinmame_files\nvram\'
    cmd: 'pinmamep.exe'
    extra_args: '-alpha_on_dmd -window -skip_disclaimer -skip_gameinfo'
python:
    cmdpath: 'c:\Python26\python.exe'
games:
    - line1: 'PinBot 2'
      line2: '(using pyProcGame)'
      gamefile: start.py
      gamepath: 'C:\P-ROC\pyprocgame-master\games\VXtra_start\'
    - line1: 'Williams PinBot ROM'
      line2: '(using Pinmame)'
      ROM: 'C:\P-ROC\pinmame_files\pb_l5'
