# Configuration file for the generic GameLauncher for P-ROC
# Rename to Loader.yaml and modify for your particular configuration

# Customize this file to your own needs --note that if your game 
# is pre-fliptronic (i.e., as a flipper relay) then you need to
# specify a flipperEnable coil in your machine_config_file so 
# the launcher can enable your flippers for game selection.  
#
# The launcher uses switches:
#     - flipperLwR
#     - flipperLwL
#     - startButton
#   to navigate the game list.
# 
# most options should be obvious.
# Note that games that run via Python require a gamefile and gamepath
# whereas pinmame ROMs (Williams/FreeWPC) should have a ROM specified
# ROMs should be placed in the pinmame path.
##################################################################### 
machine_config_file: /home/pi/VXtra_start/config/Pinbot.yaml
title: 'PinBot 2'
instructions_line_1: 'Choose game with flippers'
instructions_line_2: 'then press START to select.'
python:
    cmdpath: 'python'
games:
    - line1: 'PinBot 2'
      line2: '(using pyProcGame)'
      gamefile: start.py
      gamepath: '/home/pi/VXtra_start/'
