# P-ROC Game Description file for Big Guns

PRPinmame:
    keyboard: on
    s11CreditDisplay: 24
    s11BallDisplay: 0
    autoPatterDetection: off

PRGame:
    machineType: wpc
    numBalls: 3
PRFlippers:
    - flipperLwL
    - flipperLwR

PRBumpers:
    - slingL
    - slingR
    #- kickback

PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #                  'NC' (normally closed.  Common for optos)

    
    tilt:
        number: S11
    not_used:
        number: S12
    startButton:
        number: S13
    enter:
        number: S14
    down:
        number: S15
    exit:
        number: S16
    slamTilt:
        number: S17
    up:
        number: S18

    ballrollTilt:
        number: S21
    outhole:
        number: S22
    trough1:
        number: S23
    trough2:
        number: S24
    trough3:
        number: S25
    not_used:
        number: S26
    invincible:
        number: S27
    not_used:
        number: S28

    LdropR:
        number: S31
    LdropM:
        number: S32
    LdropL:
        number: S33
    RdropL:
        number: S34
    RdropM:
        number: S35
    RdropR:
        number: S36
    outlaneL:
        number: S37
    outlaneR:
        number: S38
        
    LguardL:
        number: S41
    LguardML:
        number: S42
    LguardM:
        number: S43
    LguardMR:
        number: S44
    LguardR:
        number: S45
    RguardL:
        number: S46
    RguardML:
        number: S47
    RguardM:
        number: S48
        
    RguardMR:
        number: S51
    RguardR:
        number: S52
    Lhole:
        number: S53
    Rhole:
        number: S54
    Lcannon:
        number: S55
    Rcannon: 
        number: S56
    Ltroll:
        number: S57
    Rtroll:
        number: S58

    OkingL: 
        number: S61
    OkingML: 
        number: S62
    OkingM:
        number: S63
    OkingMR:
        number: S64
    OkingR:
        number: S65
    notused:
        number: S66
    flipperLwL:
        number: S67
    flipperLwR:
        number: S68
        
# Ltenpoint op een notused switch gezet
    notused:
        number: S71
    notused: 
        number: S72        
    notused: 
        number: S73
    flipperLwL: 
        number: S74
    flipperLwR: 
        number: S75
    shooterLane: 
        number: S76
    Lloop:
        number: S77
    Rloop:
        number: S78
        
    railup:
        number: S81
    wl:
        number: S82
    tower:
        number: S83
    Loutlane:
        number: S84
    Routlane:
        number: S85
    notused:
        number: S86
    slingL:
        number: S87
    slingR:
        number: S88



PRCoils:
    flipperLwRMain:
        number: FLRM
    flipperLwRHold:
        number: FLRH
    flipperLwLMain:
        number: FLLM
    flipperLwLHold:
        number: FLLH

    outhole:
        number: C01
    trough:
        number: C02
    ballpopper_LwR_man:
        number: C03
    Leject_Cbackbox_:
        number: C04
    Reject_Lcannon: 
        number: C05
    Lcannon_Rcannon: 
        number: C06
    Rcannon_Ltroll_guns:
        number: C07
    knocker_Rtroll_guns:
        number: C08
    GI_L:
        number: C09
    GI_R:
        number: C10
##    GI_B:
##        number: C11
    GIrelay:
        number: C11
    ACselect:
        number: C12
    Rdroptarget:
        number: C13
    flipperpost:
        number: C14
## Tijdelijk shakermotor op invincible flasher
    invincible:
        number: C30
    shaker_motor:
        number: C15
    bboxflashers:
        number: C16
    Okc:
        number: C17
    kickback:
        number: C18
    right_gate:
        number: C19
    Ldroptarget:
        number: C20
    slingL:
        number: C21
    slingR:
        number: C22 
    flipperEnable:
        number: C23
#    shaker_motor:
#        number: C24



PRLamps:
    OkingL: 
        number: L11
    OkingML: 
        number: L12
    OkingM:
        number: L13
    OkingMR:
        number: L14
    OkingR:
        number: L15        
    invincible:
        number: L16
    shootagain:
        number: L17
    railup:
        number: L18
    Oextraball:
        number: L21
    C50k:
        number: L22
    C100k:
        number: L23
    C150k:
        number: L24
    C200k:
        number: L25
    Cspecial:
        number: L26
    kickback:
        number: L27
    Rgateopen:
        number: L28        
    LdropR:
        number: L31
    LdropM:
        number: L32
    LdropL:
        number: L33
    RdropL:
        number: L34
    RdropM:
        number: L35
    RdropR:
        number: L36
        
    Lextraball:
        number: L37
    Rextraball:
        number: L38
        
    LguardL:
        number: L41
    LguardML:
        number: L42
    LguardM:
        number: L43
    LguardMR:
        number: L44
    LguardR:
        number: L45
    RguardL:
        number: L46
    RguardML:
        number: L47
    RguardM:
        number: L48
    RguardMR:
        number: L51
    RguardR:
        number: L52        
    LholeT:
        number: L53
    RholeT:
        number: L54
    LholeB:
        number: L55
    RholeB:
        number: L56
    Lspecial:
        number: L57
    Rspecial:
        number: L58
    2x:
        number: L61
    3x:
        number: L62
    4x:
        number: L63
    5x:
        number: L64
    6x:
        number: L65
    7x:
        number: L66
    8x:
        number: L67
    9x:
        number: L68
    OLL:
        number: L71
    OLML:
        number: L72
    OLM:
        number: L73
    OLMR:
        number: L74
    OLR:
        number: L75
    2xscore:
        number: L76
    Lround:
        number: L77
    Rround:
        number: L78
    ORL:
        number: L81
    ORML:
        number: L82
    ORM:
        number: L83
    ORMR:
        number: L84
    ORR:
        number: L85
    wl:
        number: L86
    Ltroll:
        number: L87
    Rtroll:
        number: L88



PRBallSave:

    pulseCoils:

    resetSwitches:
#        shooterR: closed
    stopSwitches:
#        popperR: active
# don't ball search if a flipper button is pressed
#        flipperLwL: closed
#        flipperLwR: closed
